#!/usr/bin/env python3
"""
RxClass -> concept_reference_term_map loader.

Builds the drug->class parent-child edges that the cdshooks reference-map
backend consumes, from the NLM RxClass API (https://rxnav.nlm.nih.gov). For a
set of RxNORM ingredient CUIs it fetches their ATC drug classes and emits:

  * rxclass-edges.csv                  portable edge list
  * rxclass-reference-terms.csv        the ATC class reference terms
  * load-rxclass-edges.sql             idempotent SQL to load both into OpenMRS

ATC codes are hierarchical by string length (J=1, J01=3, J01C=4, J01CA=5), so
the class hierarchy (J01CA NARROWER-THAN J01C NARROWER-THAN J01 ...) is derived
from the codes themselves — no extra API calls. A drug allergen mapped to a
broad ATC class (e.g. J01C = penicillins) will then subsume any drug whose CUI
rolls up to it.

Usage:
  # CUIs one per line (e.g. extracted from concept_reference_term):
  python3 rxclass_loader.py CUIS_FILE --outdir ./out [--relaSource ATC]

This tool only WRITES files; review load-rxclass-edges.sql before applying it.
Requires network access to rxnav.nlm.nih.gov.
"""
import argparse
import csv
import json
import os
import sys
import time
import urllib.request

RXNAV = "https://rxnav.nlm.nih.gov/REST/rxclass/class/byRxcui.json"
RXNORM_SOURCE = "RxNORM"
ATC_SOURCE = "ATC"
NARROWER = "NARROWER-THAN"

# ATC level lengths (chars). A code's parent is the next-shorter level.
ATC_LEVELS = [1, 3, 4, 5]


def fetch_atc_classes(cui, rela_source):
    url = f"{RXNAV}?rxcui={cui}&relaSource={rela_source}"
    try:
        with urllib.request.urlopen(url, timeout=20) as r:
            data = json.load(r)
    except Exception as e:  # network / parse — skip this CUI, keep going
        print(f"  ! {cui}: {e}", file=sys.stderr)
        return {}
    out = {}
    for info in data.get("rxclassDrugInfoList", {}).get("rxclassDrugInfo", []):
        c = info["rxclassMinConceptItem"]
        out[c["classId"]] = c["className"]
    return out


def atc_parent(code):
    """Next-shorter ATC level for a code, or None at the top."""
    lvls = [n for n in ATC_LEVELS if n < len(code)]
    return code[: lvls[-1]] if lvls else None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("cuis_file", help="file with one RxNORM CUI per line")
    ap.add_argument("--outdir", default="rxclass-out")
    ap.add_argument("--relaSource", default="ATC")
    ap.add_argument("--sleep", type=float, default=0.1, help="delay between API calls")
    args = ap.parse_args()
    os.makedirs(args.outdir, exist_ok=True)

    cuis = [ln.strip() for ln in open(args.cuis_file) if ln.strip()]
    edges = set()          # (child_code, child_src, parent_code, parent_src)
    class_names = {}       # atc_code -> name

    print(f"Fetching {args.relaSource} classes for {len(cuis)} CUIs ...", file=sys.stderr)
    for cui in cuis:
        classes = fetch_atc_classes(cui, args.relaSource)
        for atc, name in classes.items():
            class_names[atc] = name
            edges.add((cui, RXNORM_SOURCE, atc, ATC_SOURCE))  # drug -> leaf class
        time.sleep(args.sleep)

    # Derive the ATC class hierarchy from code prefixes.
    for atc in list(class_names):
        child = atc
        parent = atc_parent(child)
        while parent:
            class_names.setdefault(parent, f"ATC {parent}")
            edges.add((child, ATC_SOURCE, parent, ATC_SOURCE))
            child, parent = parent, atc_parent(parent)

    # --- write portable edge list ---
    edges_csv = os.path.join(args.outdir, "rxclass-edges.csv")
    with open(edges_csv, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["child_code", "child_source", "map_type", "parent_code", "parent_source"])
        for c_code, c_src, p_code, p_src in sorted(edges):
            w.writerow([c_code, c_src, NARROWER, p_code, p_src])

    # --- write the ATC class reference terms ---
    terms_csv = os.path.join(args.outdir, "rxclass-reference-terms.csv")
    with open(terms_csv, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["source", "code", "name"])
        for atc, name in sorted(class_names.items()):
            w.writerow([ATC_SOURCE, atc, name])

    # --- write idempotent loader SQL ---
    sql = os.path.join(args.outdir, "load-rxclass-edges.sql")
    with open(sql, "w") as f:
        f.write("-- Generated by rxclass_loader.py. Review before applying.\n")
        f.write("-- Loads the ATC drug-class source, reference terms, and the\n")
        f.write("-- drug->class / class->class NARROWER-THAN edges.\n\n")
        f.write(
            "INSERT INTO concept_reference_source (name, description, hl7_code, creator, date_created, retired, uuid)\n"
            "SELECT 'ATC','WHO ATC drug classification (RxClass)','ATC',1,NOW(),0,UUID() FROM dual\n"
            "WHERE NOT EXISTS (SELECT 1 FROM concept_reference_source WHERE name='ATC');\n\n"
        )
        for atc, name in sorted(class_names.items()):
            safe = name.replace("'", "''")
            f.write(
                "INSERT INTO concept_reference_term (concept_source_id, code, name, creator, date_created, retired, uuid)\n"
                f"SELECT (SELECT concept_source_id FROM concept_reference_source WHERE name='ATC' LIMIT 1),"
                f"'{atc}','{safe}',1,NOW(),0,UUID() FROM dual\n"
                f"WHERE NOT EXISTS (SELECT 1 FROM concept_reference_term t JOIN concept_reference_source s"
                f" ON s.concept_source_id=t.concept_source_id WHERE t.code='{atc}' AND s.name='ATC');\n"
            )
        f.write("\n")
        for c_code, c_src, p_code, p_src in sorted(edges):
            f.write(
                "INSERT INTO concept_reference_term_map (term_a_id, term_b_id, a_is_to_b_id, creator, date_created, uuid)\n"
                "SELECT ta.concept_reference_term_id, tb.concept_reference_term_id,\n"
                "       (SELECT concept_map_type_id FROM concept_map_type WHERE name='NARROWER-THAN' LIMIT 1),\n"
                "       1, NOW(), UUID()\n"
                f"FROM concept_reference_term ta JOIN concept_reference_source sa ON sa.concept_source_id=ta.concept_source_id\n"
                f"   , concept_reference_term tb JOIN concept_reference_source sb ON sb.concept_source_id=tb.concept_source_id\n"
                f"WHERE ta.code='{c_code}' AND sa.name='{c_src}' AND tb.code='{p_code}' AND sb.name='{p_src}'\n"
                "  AND NOT EXISTS (SELECT 1 FROM concept_reference_term_map m\n"
                "      WHERE m.term_a_id=ta.concept_reference_term_id AND m.term_b_id=tb.concept_reference_term_id);\n"
            )

    print(f"Wrote {len(edges)} edges, {len(class_names)} ATC classes to {args.outdir}/", file=sys.stderr)
    print(f"  {edges_csv}\n  {terms_csv}\n  {sql}", file=sys.stderr)


if __name__ == "__main__":
    main()
